# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Minecraft / NeoForge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.222
loader_version_range=[4,)

# Parchment mappings
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Mod metadata
mod_id=kamaeninfo
mod_name=Kamaen Info
mod_license=MIT
mod_version=0.1.0
mod_group_id=com.anw.kamaen
mod_authors=anweat
mod_description=Kamaen Info explores material spectra, information systems, hardware automation, artificial horizons, and dimension creation.

